#!/bin/bash
# vim: set ts=4 sw=4 sts=4 et :

PLUGIN_DIR="`dirname $0`"

INSTALLDIR=$1
DIST=$2

RPM_VERSION="$(rpm --version | awk '{print $3}')"

if [ "$(printf '%s\n' "$RPM_VERSION" "4.14.0" | sort -V | head -n1)" == "4.14.0" ]; then
    PGP_INVALID='SIGNATURES NOT OK'
    PGP_NOTSIGNED='signatures OK'
else
    PGP_INVALID='PGP'
    PGP_NOTSIGNED='pgp'
fi

set -e
if [ "${VERBOSE:-0}" -ge 2 -o "${DEBUG:-0}" -eq 1 ]; then
    set -x
else
    YUM_OPTS="$YUM_OPTS -q"
fi

DOWNLOADDIR="${CACHEDIR}/base_rpms"

YUM="yum --downloaddir=${DOWNLOADDIR} --downloadonly install"
if type yumdownloader >/dev/null 2>/dev/null; then
    # debian does not have --downloadonly plugin
    YUM="yumdownloader --resolve --destdir=${DOWNLOADDIR}"
elif type dnf >/dev/null 2>/dev/null; then
    YUM="dnf $YUM_OPTS --releasever "${DIST#fc}" --downloaddir=${DOWNLOADDIR} --downloadonly install"
fi

if ! [ -f "${INSTALLDIR}/tmp/.prepared_base" ]; then
    echo "-> Initializing RPM database..."
    RPM_OPTS=()
    if [ -e /etc/debian_version ]; then
	    # Debian by default keep rpmdb in ~/.rpmdb
	    RPM_OPTS+=("--define=_dbpath %{_var}/lib/rpm")
    fi
    rpm "${RPM_OPTS[@]}" --initdb --root=${INSTALLDIR}
    rpm "${RPM_OPTS[@]}" --import --root=${INSTALLDIR} \
        ${PLUGIN_DIR}/keys/RPM-GPG-KEY-fedora-${DIST#fc}-primary

    echo "-> Retreiving core RPM packages..."
    INITIAL_PACKAGES="filesystem setup fedora-release"
    if [ "${DIST#fc}" -ge 22 ]; then
        INITIAL_PACKAGES="$INITIAL_PACKAGES dnf dnf-plugins-core"
    else
        INITIAL_PACKAGES="$INITIAL_PACKAGES yum yum-utils"
    fi
    if [ "${DIST#fc}" -ge 25 ]; then
        # libcrypt conflicts with libcrypt-nss and yumdownloader is stupid
        # enough to try them both
        INITIAL_PACKAGES="--exclude=libcrypt $INITIAL_PACKAGES"
    fi
    
    if [ "${DIST#fc}" -ge 26 ]; then
        # coreutils conflicts with coreutils-single
        INITIAL_PACKAGES="--exclude=coreutils-single $INITIAL_PACKAGES"
    fi

    if [ "${DIST#fc}" -ge 27 ]; then
        # curl-minimal conflicts with curl, same for libcurl
        INITIAL_PACKAGES="--exclude=curl --exclude=libcurl $INITIAL_PACKAGES"
    fi

    mkdir -p "${DOWNLOADDIR}"
    yumconf=$(mktemp)

    # For defined mirroris in builder.conf we need to delete the metalink option
    # in the repo file because baseurl seems to not override the metalink
    if [ "x${FEDORA_MIRROR}" != "x" ]; then
        awk '
        BEGIN {
            mirror=ARGV[1];     delete ARGV[1];
            releasever=ARGV[2]; delete ARGV[2];
        }
        {
            gsub("^metalink", "#metalink");
            gsub("^#baseurl=.*/(linux|fedora)/", "baseurl=" mirror "/");
            gsub("\\$releasever", releasever);
            print;
        }' "${FEDORA_MIRROR%/}" "${DIST#fc}" \
            < "${PLUGIN_DIR}"/yum-bootstrap.conf \
            > "$yumconf"
    else
        sed -e "s/\\\$releasever/${DIST#fc}/g" \
            < "${PLUGIN_DIR}"/yum-bootstrap.conf \
            > "$yumconf"
    fi

    $YUM -c "$yumconf" -y \
        --installroot="${INSTALLDIR}" \
        ${INITIAL_PACKAGES}
    rm -f "$yumconf"

    echo "-> Verifying signatures..."
    set +x
    for file in "${DOWNLOADDIR}"/*; do
        result=$(rpm "${RPM_OPTS[@]}" --root=${INSTALLDIR} --checksig "${file}") || {
            echo "Filename: ${file} failed verification.  Exiting!"
            exit 1
        }
        result_status="${result##*:}"
        echo "${result_status}" | grep -q "$PGP_INVALID" && {
            echo "Filename: ${file} contains an invalid PGP signature. Exiting!"
            exit 1
        }
        echo "${result_status}" | grep -q "$PGP_NOTSIGNED" || {
            echo "Filename: ${file} is not signed.  Exiting!"
            exit 1
        }
    done
    echo "-> Printing hashes of downloaded packages:"
    sha256sum "${DOWNLOADDIR}/"*.rpm
    if [ "${VERBOSE:-0}" -ge 2 -o "${DEBUG:-0}" -eq 1 ]; then
        set -x
    fi

    echo "-> Installing core RPM packages..."
    rpm "${RPM_OPTS[@]}" -U --replacepkgs --root="${INSTALLDIR}" "${DOWNLOADDIR}/"*.rpm || exit 1
    for f in null urandom zero random console; do
        cp -a /dev/$f $INSTALLDIR/dev/
    done

    # TODO: check if there is a way to force baseurl to override metalink
    if [ "x$FEDORA_MIRROR" != "x" ]; then
        sed -i "s/^metalink/#metalink/g" "${INSTALLDIR}/etc/yum.repos.d/fedora.repo" "${INSTALLDIR}/etc/yum.repos.d/fedora-updates.repo"
        sed -i "s/#baseurl/baseurl/g" "${INSTALLDIR}/etc/yum.repos.d/fedora.repo" "${INSTALLDIR}/etc/yum.repos.d/fedora-updates.repo"
    fi

    touch "${INSTALLDIR}/tmp/.prepared_base"
fi
