#!/bin/sh

if [ $# -lt 2 ]; then
    echo "Usage: $0 input output" >&2
    exit 1
fi

sed -e "s:@VERSION@:`cat ${ORIG_SRC}/version 2>/dev/null`:g" \
    -e "s:@REL@:`cat ${ORIG_SRC}/rel 2>/dev/null || echo 1`:g" \
    -e "s:@BACKEND_VMM@:${BACKEND_VMM}:g" \
    $1 > $2

# TODO: update changelog
