#!/bin/bash
# vim: set ts=4 sw=4 sts=4 et :

set -e
if [ "${VERBOSE:-0}" -ge 2 ] || [ "${DEBUG:-0}" -eq 1 ]; then
    set -x
fi

localdir="$PWD"
scriptdir="$(dirname "$(readlink -f "$0")")"
builderdir="$scriptdir/../"

# shellcheck source=scripts/functions.sh
source "$scriptdir/functions.sh"

releasever="${1//fc}"
package="$2"
src_rpm="$3"
src_file="${*:4}"

errecho() {
    >&2 echo "$@"
}

exit_get_sources() {
    local exit_code=$?

    # Clean
    rm -rf "$tmpdir"

    exit "${exit_code}"
}

if [ "x$releasever" != "x" ]; then
    if [[ ! "$releasever" =~ ^[1-9][0-9]$ ]] && [ "$releasever" != "rawhide" ]; then
        errecho "Invalid release format"
        exit 1
    fi
else
    errecho "Please provide Fedora release"
    exit 1
fi

trap 'exit_get_sources' 0 1 2 3 6 15

if [ "x$src_file" != "x" ] && [ "x$releasever" != "x" ]; then
    # download rpm
    tmpdir="$(mktemp -d -p "$localdir")"
    # shellcheck disable=SC2086
    dnf -q download --destdir="$tmpdir" --source --releasever="$releasever" "$package"
    mv "$tmpdir/$src_rpm" "$tmpdir/$src_rpm.UNTRUSTED"

    # check signature
    mkdir -p "$tmpdir/rpmdb"
    key="$builderdir/keys/RPM-GPG-KEY-fedora-$releasever-primary"
    rpmkeys --dbpath="$tmpdir/rpmdb" --import "$key"
    { rpmkeys --dbpath="$tmpdir/rpmdb" --checksig "$tmpdir/$src_rpm.UNTRUSTED" | grep -q 'signatures OK' ; } || { errecho "Failed to check signature"; exit 1; }
    mv "$tmpdir/$src_rpm.UNTRUSTED" "$tmpdir/$src_rpm"

    # get sources
    for src in $src_file
    do
        # shellcheck disable=2094
        rpm2cpio "$tmpdir/$src_rpm" | cpio --quiet -i --to-stdout "$src" > "$src"
    done
fi
