#!/bin/bash

# Default redirection or errors
ERR_OUTPUT="/dev/null"

set -e
if [ "${VERBOSE:-0}" -ge 2 -o "${DEBUG:-0}" -eq 1 ]; then
    set -x
    ERR_OUTPUT="/dev/stderr"
fi

if [ $# -lt 2 ]; then
    echo "Usage: $0 file.spec field" >&2
    exit 1
fi

[[ "x$(basename ${1}.in)" == "x.in" ]] && exit 0

if [ -r "${1}.in" ]; then
    #rpm -q $RPM_QUERY_DEFINES --qf "$2" --specfile <(`dirname $0`/generate-spec "${1}.in" /dev/stdout) 2>/dev/null
    # need to create a file due to a bug in process substitution (e.g. artwork package)
    tmp_spec=$(mktemp --tmpdir tmp.XXXXXX.spec)
    $(dirname $0)/generate-spec "${1}.in" "${tmp_spec}" 2> $ERR_OUTPUT
    rpm -q $RPM_QUERY_DEFINES --qf "$2" --specfile "${tmp_spec}" 2> $ERR_OUTPUT
    rm -f "${tmp_spec}"
else
    rpm -q $RPM_QUERY_DEFINES --qf "$2" --specfile "$1" 2> $ERR_OUTPUT
fi
