#!/bin/bash

set -e
if [ "${VERBOSE:-0}" -ge 2 -o "${DEBUG:-0}" -eq 1 ]; then
    set -x
fi

if [ $# -lt 2 ]; then
    echo "Usage: $0 file.spec field" >&2
    exit 1
fi

if [ -r "${1}.in" ]; then
    #rpm -q $RPM_QUERY_DEFINES --qf "$2" --specfile <(`dirname $0`/generate-spec "${1}.in" /dev/stdout) 2>/dev/null
    # need to create a file due to a bug in process substitution (e.g. artwork package)
    $(dirname $0)/generate-spec "${1}.in" "${1}" 2>/dev/null
    rpm -q $RPM_QUERY_DEFINES --qf "$2" --specfile "$1" 2>/dev/null
    rm -rf "${1}"
else
    rpm -q $RPM_QUERY_DEFINES --qf "$2" --specfile "$1" 2>/dev/null
fi
